//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CricketerApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Cricketer
    {
        public Cricketer()
        {
            this.Cricketer_Details = new HashSet<Cricketer_Details>();
            this.Cricketer_ODI_Statistics = new HashSet<Cricketer_ODI_Statistics>();
            this.Cricketer_Test_Statistics = new HashSet<Cricketer_Test_Statistics>();
        }
    
        public int ID { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 4)]
        public string Name { get; set; }

        [Required]
        [Range(1, 500)]
        public Nullable<int> ODI { get; set; }

        [Required]
        [Range(1, 500)]
        public Nullable<int> Test { get; set; }
        
        [Required]
        public string Grade { get; set; }
    
        public virtual ICollection<Cricketer_Details> Cricketer_Details { get; set; }
        public virtual ICollection<Cricketer_ODI_Statistics> Cricketer_ODI_Statistics { get; set; }
        public virtual ICollection<Cricketer_Test_Statistics> Cricketer_Test_Statistics { get; set; }
    }
}
